# Generated by Django 5.0.6 on 2024-06-23 09:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_blog_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='publication_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
